### ISSUE TITLE
Multiple options can be viewed at same time in mobile view

### ISSUE THREAD

**Issue by abhinandarun-02** [Takashi069/autodeck#11]
![image](https://user-images.githubusercontent.com/73401380/202860392-a16736a1-ddb6-4424-bced-5043bb0cabff.png)

**Comment by abhinandarun-02** [comment]
In mobile version multiple options can be selected
Only 1 option should be selected at a time

**Comment by jcachinho** [comment]
Hello @abhinandarun-02 I can check this issue.

One question: If we click the first option (which will enable the shadow background), the floating menu should be hidden until we close the option ? Or still visible but not allow any click ?

Thanks.

**Comment by Takashi069** [comment]
@jcachinho It would be preferable if the floating menu is not hidden. Rather when clicking on another option, current pop-up gets replaced by the new pop-up.

Just wait for @abhinandarun-02 's confirmation before proceeding.

**Comment by abhinandarun-02** [comment]
Yeah, that's what I meant.

> @jcachinho It would be preferable if the floating menu is not hidden. Rather when clicking on another option, current pop-up gets replaced by the new pop-up.
> 
> Just wait for @abhinandarun-02 's confirmation before proceeding.

**Comment by Takashi069** [comment]
Issue Fixed with #18 by @jcachinho
