### ISSUE TITLE
Change Titlebar Logo to something more fitting

### ISSUE THREAD

**Issue by Takashi069** [Takashi069/autodeck#12]
The titlebar logo can be changed as the logo does not resemble what the website aims to achieve

![WhatsApp Image 2022-11-19 at 21 45 09](https://user-images.githubusercontent.com/73834506/202860870-028a70db-0d42-4393-8d12-c00ef9f2ce74.jpeg)

**Comment by jcachinho** [comment]
Hello @Takashi069 I can contribute this issue. This titlebar logo would be great ?

![image](https://user-images.githubusercontent.com/48864329/202866715-f2ec4842-1257-4df0-91fe-02094aff8154.png)


 If not what type of icon would you prefer ?

Thanks

**Comment by Takashi069** [comment]
This would be great.

But  won't it appear too dark when viewed on a browser with dark theme enabled ? 

I'm assuming that the white background would be removed 😅

**Comment by jcachinho** [comment]
I added the following line on html :

![image](https://user-images.githubusercontent.com/48864329/202871677-a687fcd0-864b-4412-94e8-104fada27061.png)

and the icon doesn't appear too dark:

![image](https://user-images.githubusercontent.com/48864329/202871714-69286881-626e-4e3f-8811-91d900a3378f.png)

**Comment by Takashi069** [comment]
@jcachinho 
We just found a better logo. I'll attach  it here  :point_down: 


![autodeck-low-resolution-logo-color-on-transparent-background](https://user-images.githubusercontent.com/73834506/202897454-974fdc73-24e9-4ff5-b1ca-d36c8840761d.png)


<br>

**Make sure you download this and save it in a asset folder and take the image from there.** 
Also, before you put in a pull request, could you **change the content** of the meta tag with the name="description" to the following: 
"Web Site showing the contact details of auto-drivers near Amrita University, Amritapuri"

Thanks for the help !  :+1:
