### ISSUE TITLE
Card goes out of bounds when hovered

### ISSUE THREAD

**Issue by abhinandarun-02** [Takashi069/autodeck#13]
![image](https://user-images.githubusercontent.com/73401380/202860900-65825b9c-ee2b-478b-a128-0616af6cbf56.png)

**Comment by Takashi069** [comment]
**Could you tell the resolution at which this occurs. ?**
It is working normally on my end
![Screenshot_20221119_215229](https://user-images.githubusercontent.com/73834506/202861021-347eaa63-7a6f-4a56-b55b-33f00fea2d3d.png)

**Comment by Takashi069** [comment]
One possible fix could be to push the grid elements to the right by the same extent  by which the navbar expands

**Comment by abhinandarun-02** [comment]
Lemme see, I will work on this one
